#!/bin/bash -e

# docker build --build-arg vcs_ref=`git rev-parse --short HEAD` --build-arg build_date=`date -u +"%Y-%m-%dT%H:%M:%SZ"` .

BASE_IMAGE="farrider/kafka"
IMAGE_VERSION="$1"

if [ -z "$IMAGE_VERSION" ]; then
  echo "No IMAGE_VERSION var specified"
  exit 1
fi

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
TARGET="$BASE_IMAGE:$IMAGE_VERSION"
docker tag "$BASE_IMAGE" "$TARGET"
docker push "$TARGET"
